name: Build Rustscan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install musl-tools -y

    - name: Build with cargo for x86_64-unknown-linux-musl
      run: cargo build --release --target=x86_64-unknown-linux-musl

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: rustscan
        path: target/x86_64-unknown-linux-musl/release/rustscan
