name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install musl-tools -y

    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true

    - name: Build
      run: cargo build --release --target=x86_64-unknown-linux-musl --verbose

    - name: List build directory
      run: ls -la target/x86_64-unknown-linux-musl/release/

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: rustscan
        path: target/x86_64-unknown-linux-musl/release/rustscan
